Initial implementation for force-unlock
charleszipp/azure-pipelines-tasks-terraform pull request #161
Opened 2020-10-15 10:18 UTC by favoretti

Sometimes ADO pipeline cancels the runs mid-run leaving stale locks hanging. This would allow people to create separate pipelines to unlock those cases.

2020-10-15 10:19 UTC, favoretti commented
@charleszipp Long time no speak. What do you think of this one?

2020-10-15 13:38 UTC, charleszipp requested changes
Thanks for this addition @favoretti ! I have experienced this occasionally as well so think this will be great addition.

Would you mind adding a test to ensure the command is being issued appropriately? Im thinking at minimum we need one test to ensure the handler issues the command as terraform expects. 

I will check in on the pipeline to make sure there are no other issues.

2020-10-15 13:41 UTC, charleszipp commented
@favoretti also would you mind updating the overview.md at the root to mention the support for this new command? I think just adding it to the list of supported commands should be good enough as there isnt much explanation needed about how to use this.

![image](https://user-images.githubusercontent.com/4292559/96137412-3cb6f680-0ec2-11eb-99a0-8ee3a3d35656.png)

2020-10-15 13:59 UTC, favoretti commented
@charleszipp will work on a test for sure, wanted to get your initial thoughts on this first before going all too deep into keystrokes :) Will try to push them tonight/tomorrow my am. Thanks for the review!

2020-10-16 13:28 UTC, charleszipp requested changes
Couple small changes then we should be good to go. Pipeline is passing for all other commands. Will add this command into the pipeline so it gets tested from there too.

2020-10-16 13:28 UTC, charleszipp commented on TerraformCLI/src/tests/terraform-force-unlock/force-unlock_spec.ts
> +        const env = require('./force-unlock-azurerm-with-secure-env-file.env').env;
@favoretti im not sure we need this test because the variables group is not enabled for `force-unlock` command.

2020-10-16 13:28 UTC, charleszipp commented on TerraformCLI/src/terraform-force-unlock.ts
> +            tasks.getInput("lockID"),
Should we disable the command options in `task.json` to prevent someone from trying to add the `-force` option or is there something else that will prevent that from being duplicated?

2020-10-16 13:33 UTC, favoretti commented on TerraformCLI/src/tests/terraform-force-unlock/force-unlock_spec.ts
> +        const env = require('./force-unlock-azurerm-with-secure-env-file.env').env;
Ah, that's true... Let me remove it.

2020-10-16 13:35 UTC, favoretti commented on TerraformCLI/src/terraform-force-unlock.ts
> +            tasks.getInput("lockID"),
Hmm, are you looking at an outdated version? I removed it, don't have it locally.

2020-10-16 13:38 UTC, charleszipp commented on TerraformCLI/src/terraform-force-unlock.ts
> +            tasks.getInput("lockID"),
Im still seeing it when adding the task from the pipeline. I think you would need to update the `commandOptions` input in task.json to enable only if command != force-unlock
![image](https://user-images.githubusercontent.com/4292559/96265395-00030200-0f8b-11eb-8e82-220a94626cc5.png)

2020-10-16 13:49 UTC, charleszipp commented on TerraformCLI/src/terraform-force-unlock.ts
> +            tasks.getInput("lockID"),
Note also not seeing the lock-id field show up either.

2020-10-16 14:01 UTC, favoretti commented on TerraformCLI/src/terraform-force-unlock.ts
> +            tasks.getInput("lockID"),
Hrm.. Let me double-check.

2020-10-20 12:20 UTC, favoretti commented on TerraformCLI/src/terraform-force-unlock.ts
> +            tasks.getInput("lockID"),
Ok, removed the announcement from overview, let's do a dark launch, I can test it on my pipelines once it works, I'll push a line into the readme.

2020-10-20 18:15 UTC, charleszipp approved these changes

2020-10-20 18:16 UTC, merged