Make `show` task present the output to the build window
charleszipp/azure-pipelines-tasks-terraform pull request #173
Opened 2020-11-20 14:03 UTC by alex-goncharov

- remove mandatory json output
 - replace json search for deletions with regexmatch

2020-11-25 17:24 UTC, favoretti commented
@charleszipp any thoughts? Happy Thanksgiving!

2020-11-25 22:59 UTC, favoretti commented
This should also fix #171

2020-12-02 08:54 UTC, alex-goncharov commented
@charleszipp, when time permits, could you please have a look at this?

2020-12-04 15:08 UTC, charleszipp requested changes

2020-12-04 15:08 UTC, charleszipp commented on TerraformCLI/src/terraform-show.ts
> +        super(name, workingDirectory, options, false);
It appears we do not need to emit the show stdout to the build logs for the updated destroy detection to work. When @HadwaAbdelhalem and I originally added this functionality we chose to hide this out of concern we would see sensitive values emitted to the build console. Curious your feedback @alex-goncharov @favoretti ? 

Could we maybe allow users to explicitly opt into show stdout to being emitted to build logs as separate PR? This way they could hide it for more secured environments such as prod, staging, etc.

2020-12-04 15:08 UTC, charleszipp commented on TerraformCLI/src/terraform-show.ts
> +        const re = /([0-9]+) to add, ([0-9]+) to change, ([0-9])+ to destroy./;
The user could still add the `-json` flag in the commandOptions field. I would suggest we keep the original parse logic in place to be used when -json flag is supplied. This will also provide a backward compatibility escape hatch if any users for some reason are depending on this flag.

2020-12-04 15:18 UTC, alex-goncharov commented on TerraformCLI/src/terraform-show.ts
> +        const re = /([0-9]+) to add, ([0-9]+) to change, ([0-9])+ to destroy./;
Ah, you mean apply the different parsing depending on whether `-json` is supplied or not?

2020-12-04 15:18 UTC, alex-goncharov commented on TerraformCLI/src/terraform-show.ts
> +        super(name, workingDirectory, options, false);
We might want to have 2 separate "show" commands then. First one shows the plan only and it will not show anything that `terraform plan` already did not. This is purely for human use, because it is quite annoying to scroll thousands of lines to get to the actual plan actions. The other mode/command is the one that produces json and can potentially show state, personally, i would not want it anywhere near my infra :).

2020-12-04 15:30 UTC, favoretti commented on TerraformCLI/src/terraform-show.ts
> +        super(name, workingDirectory, options, false);
We can make a separate command `showPlan` or so, to do what you wanna do Alex, i.e. just show what's changed without refresh lines?

2020-12-04 15:34 UTC, alex-goncharov commented on TerraformCLI/src/terraform-show.ts
> +        super(name, workingDirectory, options, false);
yes, let me do that

2020-12-04 15:42 UTC, charleszipp commented on TerraformCLI/src/terraform-show.ts
> +        super(name, workingDirectory, options, false);
Originally this feature was only implemented for destroy detection. I would suggest we scope this PR to changing the destroy detection strategy without modifying what is output to the build logs. 

Lets do a separate issue to enhance show to include plan info in the build logs. This should resolve #171 more immediately and give us some space to make sure we think about what should/shouldn't go into the build log.

Sound good @favoretti @alex-goncharov?

2020-12-04 15:43 UTC, charleszipp commented on TerraformCLI/src/terraform-show.ts
> +        const re = /([0-9]+) to add, ([0-9]+) to change, ([0-9])+ to destroy./;
Yes, if -json is included in the `commandOptions`, then use the original parse strategy. **This will require that we keep the `isSilent` flag set to `true` or else we could risk exposing state.**

2020-12-07 14:40 UTC, charleszipp commented on TerraformCLI/src/terraform-show.ts
> +        super(name, workingDirectory, options, false);
Thanks for sharing the additional context @favoretti. 

Since the json output is the one that has the potential to leak sensitive state values, perhaps we should just block the potential for a user to have the json output logged to the console. In previous versions, there was no way they could get the json output to the console since the task itself added it and, always ran silently. So perhaps the easiest way to continue this is to prevent them from specifying the -json option.

To do this, I would propose we disable the 'commandOptions' input for show. We then run show without -json option as Alex has implemented with this PR and parse for destroy via the regex he already implemented. I believe this should satisfy the two immediate needs (#171 and what you shared) while reducing the risk of exposing sensitive state.

Thoughts?

2020-12-07 14:42 UTC, charleszipp commented on TerraformCLI/src/terraform-show.ts
> +        const re = /([0-9]+) to add, ([0-9]+) to change, ([0-9])+ to destroy./;
See comment above @alex-goncharov. Proposing we prevent users from specifying -json option so we can safely emit the show output to build logs. If accepted, this can remain as was originally implemented.

2020-12-14 14:37 UTC, charleszipp commented
@alex-goncharov should we abandon this PR in favor of the other two you have in progress?

2020-12-15 16:34 UTC, favoretti commented
I believe this can be closed now in favor of #179. @alex-goncharov let me know if this should be re-opened.

2020-12-15 16:34 UTC, closed without merging