Uploads `terraform plan` summary instead of complete plan output
charleszipp/azure-pipelines-tasks-terraform pull request #248
Opened 2021-03-05 11:51 UTC by alex-goncharov

- adds separate parameter for the plan output: planOutputFilePath to be used lated with `terraform show` command
- when publish results is requested, run terraform show command with planOutputFilePath as the input file.
- add ability to switch off stdout buffer transforts (not sure why are they there in the first place).
- replace content of the attachment with `terraform show` output

2021-03-05 12:00 UTC, alex-goncharov commented
@charleszipp @favoretti 

I would like to replace the complete `terraform plan` output with only the summary of the plan, pretty much like it was intended in my original draft. The main reason we have started this is to be able to quickly glance at the proposed plan instead of scrolling thousands of lines to get to the bottom just to see that this one parameter of this single resource is planned to be changed the way it should. 

Check if the approach I've taken is something that can go forward, considering the fact that there will be another `terraform show` run with `-json` output, to upload plan summary.

2021-03-05 13:31 UTC, favoretti requested changes
The reason tests are failing is because you haven't added your new parameter to the pipelines configuration that are running the tests, hence the output of the plan differs from what you'd expect since it prints your error message instead of a plan.

2021-03-05 13:31 UTC, favoretti commented on tasks/terraform-cli/src/commands/tf-plan.ts
> +    planOutputFilePath: non-empty string that identifies this plan. This has
This should be `publishPlanResults` I assume?

2021-03-05 14:05 UTC, alex-goncharov commented on tasks/terraform-cli/src/commands/tf-plan.ts
> +    planOutputFilePath: non-empty string that identifies this plan. This has
both fixed, 3 tests remaining.

2021-03-05 14:42 UTC, alex-goncharov commented on tasks/terraform-cli/src/commands/tf-plan.ts
> +    planOutputFilePath: non-empty string that identifies this plan. This has
it must be , indeed

2021-03-08 14:33 UTC, charleszipp requested changes
Appreciate the contribution as always @alex-goncharov. I was hoping to add the summary once we got through the initial release. There was quite a bit of work just to support testing the UI extension so wanted to focus on that first.

As for the approach in this PR I would suggest rethinking a few things. 
1) We need to maintain existing functionality. Since the plan detail is already showing we need to make sure that continues to show since its already been released in the wild.
2) The extra plan out configuration: I dont believe its going to be intuitive for users to know that this is required for publishing plan results to work. If we absolutely need the plan output then I would suggest trying to detect it from command options first. If it wasnt provided, then the task can just generate one on behalf of the user. This way the user doesnt have to update their pipeline to start saving plan output if they didnt need it in the first place.
3) Do we need to run show to get the summary? If we could avoid the need to run show, I think much of this would be simplified. I was hoping that we might be able to parse the plan detail to extract the summary information. Terraform always has a summary line at the end that reports how many resources will be created, destroyed, and updated. Can we regex this and use it for our summary?

2021-03-09 17:23 UTC, favoretti commented
@charleszipp By plan detail we actually mean not showing the refresh part of the plan. The actual details are the ones that are interesting, but we have plans with 3000+ resources in them and scrolling through refresh phase of it is just useless, hence the initial idea of this tab - show only what's changing, not state refreshes.

2021-03-09 17:42 UTC, charleszipp commented
> @charleszipp By plan detail we actually mean not showing the refresh part of the plan. The actual details are the ones that are interesting, but we have plans with 3000+ resources in them and scrolling through refresh phase of it is just useless, hence the initial idea of this tab - show only what's changing, not state refreshes.

Thanks @favoretti that helps. To double check my understanding, the reason for using `show` is that it will produce the change summary without all the refresh logs correct? If so, lets modify this to do what I suggested in the bullet 2. Check the command options for the existence of `-out`. If one exists, use that when running show. Otherwise, append on behalf of the user when running plan. In the case were we provide it on their behalf, make sure the plan output is saved to agent temp directory so its deleted after task is finished. That should remove the need for extra configuration.

2021-03-09 17:48 UTC, favoretti commented
@charleszipp Yes sir, you are completely correct. I'll leave the implementation suggestion up to @alex-goncharov here, since it's his code, unless he wants me to jump in.

2021-03-11 15:22 UTC, favoretti commented
#249 will take care of this, closing.

2021-03-11 15:22 UTC, closed without merging