chop plan generation output off and leave only summary when publishing
charleszipp/azure-pipelines-tasks-terraform pull request #249
Opened 2021-03-10 09:50 UTC by alex-goncharov

This trims the `terraform plan` state refresh output and keeps only the plan summary for publishing. Also shoots some warnings with task agent to be seen on the main page/tab of the build summary (super handy, trust me)

    - add decorator that keeps terraform command output as is
    - expose task logging in task agent

Supersedes #248

2021-03-10 11:31 UTC, alex-goncharov commented
@charleszipp this is a stab at parsing the plan, which completely relies on the plan  output and does not run display. On the other hand it wants to always run with -detailed-exit code. But since change detection was always there and it does not work completely without the exit code, we should be fine.

2021-03-10 15:57 UTC, charleszipp requested changes
Thanks @alex-goncharov for reworking the approach. I like the approach and think this will open some interesting possibilities. 

Only significant issue is with the way detailed exitcode is being added. If we add this always, it will change how the environment variables are set. This could break pipelines if they have conditions that only check for == or != 0. Lets add this on their behalf only if publishPlanResults exists so they can opt-into the breaking change for these env vars.

2021-03-10 15:57 UTC, charleszipp commented on tasks/terraform-cli/src/commands/tf-plan.ts
> +        ctx.setVariable("TERRAFORM_PLAN_HAS_CHANGES", (exitCode === terraformPlanOkHasChanges).toString(), false);
Lets make sure this still reports as it did before if `publishPlanResults` does not exist (see earlier comment about only adding detailed exit code when publishPlanResults exists). Currently, if they dont provide -detailed-exitcode and terraform returns exit code 0, its set to true. There should be existing tests that check this behavior that should pass if this works.

2021-03-10 15:57 UTC, charleszipp commented on tasks/terraform-cli/src/commands/tf-plan.ts
> +        this.taskAgent.warning(`This plan is going to create ${toAdd} resources.`)
Inject ILogger via the constructor. See [tf-output for example](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/f4af431726ed3d3f795ac89ad3dbd38963f1d031/tasks/terraform-cli/src/commands/tf-output.ts#L10). You can then do `this.logger.warning`. That will do what you added to task-agent.

You will also need to update task.ts to make sure the TerraformPlan command is instantiated with the logger instance from task.ts.

2021-03-10 15:58 UTC, charleszipp commented on tasks/terraform-cli/src/commands/tf-plan.ts
> +        ctx.setVariable("TERRAFORM_PLAN_HAS_CHANGES", (exitCode === terraformPlanOkHasChanges).toString(), false);
The existing tests I mentioned are failing now but, should start passing once this behaves as it did before when `publishPlanResults` is not set.

2021-03-10 20:20 UTC, alex-goncharov commented on tasks/terraform-cli/src/commands/tf-plan.ts
> +        ctx.setVariable("TERRAFORM_PLAN_HAS_CHANGES", (exitCode === terraformPlanOkHasChanges).toString(), false);
fixed

2021-03-10 20:21 UTC, alex-goncharov commented on tasks/terraform-cli/src/commands/tf-plan.ts
> +            .withDetailedExitCode(ctx.commandOptions)
reverted logic back for the case when publishing is not configured and no -detailed-exitcode is given. The detailed code is forcefully set when publishing is requested though.

2021-03-10 21:47 UTC, alex-goncharov commented on tasks/terraform-cli/src/commands/tf-plan.ts
> +        this.taskAgent.warning(`This plan is going to create ${toAdd} resources.`)
fixed

2021-03-11 14:56 UTC, charleszipp approved these changes
LGTM! Thanks so much @alex-goncharov for all your hard work on this. I think this will be very helpful to others that dont want to look at 100's or 1000's of lines of refresh logs in the plan view.

2021-03-11 15:57 UTC, merged